/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.AbsPlace;
import Core.Arc;
import Core.Element;
import Core.Graph;
import Core.Node;
import Core.Place;
import Core.Resource;
import Core.Transition;
import GUI.View.DiagramPanel;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author Miso
 */
public class PropertiesMenu extends javax.swing.JPanel {

    private String elementName;
    private String elementWidth;
    private String elementHeight;
    private String elementFontSize;
    private String elementMarking;
    private boolean elementStart;
    private boolean elementEnd;
    private Color elementColor;
    private Graph graph;
    private DiagramPanel window;
    private Element element;

    /**
     * Creates new form PropertiesParentMenu
     */
    public PropertiesMenu() {
        initComponents();
        setListeners();
    }

    private void setListeners() {
        nameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        nameText.selectAll();
                    }
                });
            }
        });

        heightText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        heightText.selectAll();
                    }
                });
            }
        });

        widthText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        widthText.selectAll();
                    }
                });
            }
        });

        fontSizeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        fontSizeText.selectAll();
                    }
                });
            }
        });

        capacityText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        capacityText.selectAll();
                    }
                });
            }
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label4 = new java.awt.Label();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        heightText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        widthText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fontSizeText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fontColorLabel = new javax.swing.JLabel();
        specific = new javax.swing.JPanel();
        endCheckBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        startCheckBox = new javax.swing.JCheckBox();
        capacityText = new javax.swing.JTextField();

        label4.setName(""); // NOI18N
        label4.setText("Width");

        jButton4.setText("Ok");

        label6.setName(""); // NOI18N
        label6.setText("Font size");

        jButton6.setText("Ok");

        setRequestFocusEnabled(false);

        jLabel1.setText("Name");
        jLabel1.setToolTipText("Name of element");

        nameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFocusLost(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        jLabel2.setText("Height");
        jLabel2.setToolTipText("GUI height of element");

        heightText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                heightTextFocusLost(evt);
            }
        });
        heightText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                heightTextKeyReleased(evt);
            }
        });

        jLabel3.setText("Width");
        jLabel3.setToolTipText("GUI width of element");

        widthText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                widthTextFocusLost(evt);
            }
        });
        widthText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                widthTextKeyReleased(evt);
            }
        });

        jLabel4.setText("Font Size");
        jLabel4.setToolTipText("Font Size");

        fontSizeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fontSizeTextFocusLost(evt);
            }
        });
        fontSizeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fontSizeTextKeyReleased(evt);
            }
        });

        jLabel5.setText("Font color");
        jLabel5.setToolTipText("Color of font");

        colorLabel.setBackground(new java.awt.Color(0, 0, 102));
        colorLabel.setForeground(new java.awt.Color(255, 255, 255));
        colorLabel.setOpaque(true);
        colorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorLabelMouseClicked(evt);
            }
        });

        jLabel6.setText("Color");
        jLabel6.setToolTipText("Color of element");

        fontColorLabel.setBackground(new java.awt.Color(0, 0, 102));
        fontColorLabel.setForeground(new java.awt.Color(255, 255, 255));
        fontColorLabel.setOpaque(true);
        fontColorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fontColorLabelMouseClicked(evt);
            }
        });

        endCheckBox.setText("End");
        endCheckBox.setToolTipText("Is place end place?");
        endCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endCheckBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Capacity");

        startCheckBox.setText("Start");
        startCheckBox.setToolTipText("Is place start place?");
        startCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCheckBoxActionPerformed(evt);
            }
        });

        capacityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityTextActionPerformed(evt);
            }
        });
        capacityText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                capacityTextFocusLost(evt);
            }
        });
        capacityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                capacityTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout specificLayout = new javax.swing.GroupLayout(specific);
        specific.setLayout(specificLayout);
        specificLayout.setHorizontalGroup(
            specificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specificLayout.createSequentialGroup()
                .addGroup(specificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(specificLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(capacityText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(startCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        specificLayout.setVerticalGroup(
            specificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specificLayout.createSequentialGroup()
                .addGroup(specificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacityText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endCheckBox)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText)
                    .addComponent(heightText)
                    .addComponent(fontSizeText)
                    .addComponent(widthText))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fontColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(specific, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameText)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fontColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorLabelMouseClicked
        JColorChooser colorChooser = new JColorChooser();
        elementColor = JColorChooser.showDialog(this, "Vyberte farbu", this.element.getColor());
        //colorLabel.setBackground(elementColor);

        element.setColor(elementColor);
        this.colorLabel.setOpaque(true);
        this.colorLabel.setBackground(elementColor);
        window.repaint();
        //this.revalidate();
        //this.repaint();
    }//GEN-LAST:event_colorLabelMouseClicked

    private void fontColorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fontColorLabelMouseClicked
        JColorChooser colorChooser = new JColorChooser();
        elementColor = JColorChooser.showDialog(this, "Vyberte farbu", this.element.getColor2());
        element.setColor2(elementColor);
        this.fontColorLabel.setOpaque(true);
        this.fontColorLabel.setBackground(elementColor);
        window.repaint();
        //this.revalidate();
        //this.repaint();
    }//GEN-LAST:event_fontColorLabelMouseClicked

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
    }//GEN-LAST:event_nameTextKeyReleased

    private void heightTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightTextKeyReleased
    }//GEN-LAST:event_heightTextKeyReleased

    private void widthTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthTextKeyReleased
    }//GEN-LAST:event_widthTextKeyReleased

    private void fontSizeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fontSizeTextKeyReleased
    }//GEN-LAST:event_fontSizeTextKeyReleased

    private void startCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startCheckBoxActionPerformed
        if (element instanceof AbsPlace) {
            AbsPlace abs = (AbsPlace) element;
            if (startCheckBox.isSelected()) {
                abs.setStart(true);
            } else {
                abs.setStart(false);
            }
        }
    }//GEN-LAST:event_startCheckBoxActionPerformed

    private void endCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endCheckBoxActionPerformed
        if (element instanceof AbsPlace) {
            AbsPlace abs = (AbsPlace) element;
            if (endCheckBox.isSelected()) {
                abs.setEnd(true);
            } else {
                abs.setEnd(false);
            }

        }
    }//GEN-LAST:event_endCheckBoxActionPerformed

    private void capacityTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capacityTextKeyReleased
    }//GEN-LAST:event_capacityTextKeyReleased

    private void capacityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacityTextActionPerformed

    private void nameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFocusLost
        if (!nameText.getText().equals("")) {
            element.setName(nameText.getText());
        }
        window.repaint();

    }//GEN-LAST:event_nameTextFocusLost

    private void heightTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heightTextFocusLost
        if (!heightText.getText().equals("")) {
            if (element instanceof AbsPlace) {
                AbsPlace abs = (AbsPlace) element;
                abs.setHeight(Integer.parseInt(heightText.getText()));
            }
            if (element instanceof Transition) {
                Transition abs = (Transition) element;
                abs.setHeight(Integer.parseInt(heightText.getText()));
            }
            if(element instanceof Node){
                Node node=(Node) element;
                node.setHeight(Integer.parseInt(heightText.getText()));
            }
            window.repaint();
        }
    }//GEN-LAST:event_heightTextFocusLost

    private void widthTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_widthTextFocusLost
        if (!widthText.getText().equals("")) {
            if (element instanceof AbsPlace) {
                AbsPlace abs = (AbsPlace) element;
                abs.setWidth(Integer.parseInt(widthText.getText()));
            }
            if (element instanceof Transition) {
                Transition abs = (Transition) element;
                abs.setWidth(Integer.parseInt(widthText.getText()));
            }
            if(element instanceof Node){
                Node node=(Node) element;
                node.setWidth(Integer.parseInt(widthText.getText()));
            }
            window.repaint();
        }
    }//GEN-LAST:event_widthTextFocusLost

    private void fontSizeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fontSizeTextFocusLost
        if (!fontSizeText.getText().equals("")) {
            element.setFontSize(Integer.parseInt(fontSizeText.getText()));
            window.repaint();
        }
    }//GEN-LAST:event_fontSizeTextFocusLost

    private void capacityTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_capacityTextFocusLost
        if (!capacityText.getText().equals("")) {
            if (element instanceof AbsPlace) {
                AbsPlace abs = (AbsPlace) element;
                abs.setMarking(Integer.parseInt(capacityText.getText()));
                if (abs instanceof Place) {
                    Place place = (Place) abs;
                    place.addMarking(Integer.parseInt(capacityText.getText()));
                } else if (abs instanceof Resource) {
                    Resource res = (Resource) abs;
                    res.setMarking(Integer.parseInt(capacityText.getText()));
                }

            } else if (element instanceof Arc) {
                Arc a = (Arc) element;
                a.setCapacity(Integer.parseInt(capacityText.getText()));
            }else if(element instanceof Node){
                Node node=(Node) element;
                node.setCapacity(Integer.parseInt(capacityText.getText()));           
            }
            window.repaint();
        }
    }//GEN-LAST:event_capacityTextFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacityText;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JCheckBox endCheckBox;
    private javax.swing.JLabel fontColorLabel;
    private javax.swing.JTextField fontSizeText;
    private javax.swing.JTextField heightText;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private javax.swing.JTextField nameText;
    private javax.swing.JPanel specific;
    private javax.swing.JCheckBox startCheckBox;
    private javax.swing.JTextField widthText;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the elementWidth
     */
    public String getElementWidth() {
        return elementWidth;
    }

    /**
     * @param elementWidth the elementWidth to set
     */
    public void setElementWidth(String elementWidth) {

        this.widthText.setText(elementWidth);
        //this.elementWidth = elementWidth;
    }

    /**
     * @return the elementHeight
     */
    public String getElementHeight() {
        return elementHeight;
    }

    /**
     * @param elementHeight the elementHeight to set
     */
    public void setElementHeight(String elementHeight) {
        //this.elementHeight = elementHeight;
        this.heightText.setText(elementHeight);
    }

    /**
     * @return the elementFontSize
     */
    public String getElementFontSize() {
        return elementFontSize;
    }

    /**
     * @param elementFontSize the elementFontSize to set
     */
    public void setElementFontSize(String elementFontSize) {
        //this.elementFontSize = elementFontSize;
        this.fontSizeText.setText(elementFontSize);
    }

    /**
     * @return the elementColor
     */
    public Color getElementColor() {
        return elementColor;
    }

    /**
     * @param elementColor the elementColor to set
     */
    public void setElementColor(Color elementColor) {
        this.elementColor = elementColor;
        //this.colorText.setText(elementColor);
    }

    /**
     * @return the elementName
     */
    public String getElementName() {
        return elementName;
    }

    /**
     * @param elementName the elementName to set
     */
    public void setElementName(String elementName) {
        //this.elementName = elementName;
        this.nameText.setText(elementName);
    }

    /**
     * @return the elementMarking
     */
    public String getElementMarking() {
        return elementMarking;
    }

    /**
     * @param elementMarking the elementMarking to set
     */
    public void setElementMarking(String elementMarking) {
        this.capacityText.setText(elementMarking);
    }

    /**
     * @return the elementStart
     */
    public boolean isElementStart() {
        return elementStart;
    }

    /**
     * @param elementStart the elementStart to set
     */
    public void setElementStart(boolean elementStart) {
        if (elementStart) {
            this.startCheckBox.setSelected(true);
        } else {
            this.startCheckBox.setSelected(false);
        }
    }

    /**
     * @return the elementEnd
     */
    public boolean isElementEnd() {
        return elementEnd;
    }

    /**
     * @param elementEnd the elementEnd to set
     */
    public void setElementEnd(boolean elementEnd) {
        if (elementEnd) {
            this.endCheckBox.setSelected(true);
        } else {
            this.endCheckBox.setSelected(false);
        }
    }

    public void loadProperties(Element currentElement, Graph graph, DiagramPanel window) {
        this.element = currentElement;
        heightText.setEnabled(true);
        widthText.setEnabled(true);
        //this.graph = graph;
        this.window = window;
        setElementName(currentElement.getName());
        setElementColor(currentElement.getColor());
        colorLabel.setBackground(currentElement.getColor());
        fontColorLabel.setBackground(currentElement.getColor2());
        setElementFontSize(Integer.toString(currentElement.getFontSize()));
        //notes.setText(currentElement.getNote());
        if (currentElement instanceof AbsPlace) {
            jLabel7.setText("Marking");
            AbsPlace current = (AbsPlace) currentElement;
            setElementWidth(Integer.toString(current.getWidth()));
            setElementHeight(Integer.toString(current.getHeight()));
            setElementMarking(Integer.toString(current.getMarking()));
            startCheckBox.setVisible(true);
            endCheckBox.setVisible(true);
            setElementEnd(current.isEnd());
            setElementStart(current.isStart());
            specific.setVisible(true);
            jLabel7.setToolTipText("Marking of place/resource");
        }
        if (currentElement instanceof Node) {
            jLabel7.setText("Marking");
            Node current = (Node) currentElement;
            setElementWidth(Integer.toString(current.getWidth()));
            setElementHeight(Integer.toString(current.getHeight()));
            setElementMarking(Integer.toString(current.getCapacity()));
            startCheckBox.setVisible(false);
            endCheckBox.setVisible(false);
            specific.setVisible(true);
            jLabel7.setToolTipText("Marking of node");
        }
        if (currentElement instanceof Transition) {
            Transition current = (Transition) currentElement;
            setElementWidth(Integer.toString(current.getWidth()));
            setElementHeight(Integer.toString(current.getHeight()));
            specific.setVisible(false);
        }
        if (currentElement instanceof Arc) {
            Arc current = (Arc) currentElement;
            widthText.setEnabled(false);
            widthText.setText("");
            heightText.setEnabled(false);
            heightText.setText("");
            jLabel7.setText("Capacity");
            capacityText.setText(current.getCapacity() + "");
            capacityText.setSize(nameText.getHeight(), nameText.getWidth());
            startCheckBox.setVisible(false);
            endCheckBox.setVisible(false);
            specific.setVisible(true);
            jLabel7.setToolTipText("Capacity of a arc");
        }
        this.revalidate();
        this.validate();
    }
}
