/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.AbsPlace;
import Core.Element;
import Core.Transition;


/**
 *
 * @author Miso
 */
public class PropertiesMenu extends javax.swing.JPanel {
    private String elementName;
    private String elementWidth;
    private String elementHeight;
    private String elementFontSize;
    private String elementColor;
    private Element element;
    /**
     * Creates new form PropertiesParentMenu
     */
    public PropertiesMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label4 = new java.awt.Label();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        label7 = new java.awt.Label();
        nameText = new javax.swing.JTextField();
        heightText = new javax.swing.JTextField();
        widthText = new javax.swing.JTextField();
        fontSizeText = new javax.swing.JTextField();
        colorText = new javax.swing.JTextField();

        label4.setName(""); // NOI18N
        label4.setText("Width");

        jButton4.setText("Ok");

        label6.setName(""); // NOI18N
        label6.setText("Font size");

        jButton6.setText("Ok");

        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        label1.setText("Name");

        label2.setName("labell"); // NOI18N
        label2.setText("Height");

        label3.setName(""); // NOI18N
        label3.setText("Width");

        label5.setName(""); // NOI18N
        label5.setText("Font size");

        label7.setName(""); // NOI18N
        label7.setText("Color");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heightText)
                    .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(widthText)
                    .addComponent(colorText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fontSizeText))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void nameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFocusLost
        element.setName(nameText.getText());
        
    }//GEN-LAST:event_nameTextFocusLost

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
      System.out.print("aaaa");        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField colorText;
    private javax.swing.JTextField fontSizeText;
    private javax.swing.JTextField heightText;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField widthText;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the elementWidth
     */
    public String getElementWidth() {
        return elementWidth;
    }

    /**
     * @param elementWidth the elementWidth to set
     */
    public void setElementWidth(String elementWidth) {
        this.widthText.setText(elementWidth);
        //this.elementWidth = elementWidth;
    }

    /**
     * @return the elementHeight
     */
    public String getElementHeight() {
        return elementHeight;
    }

    /**
     * @param elementHeight the elementHeight to set
     */
    public void setElementHeight(String elementHeight) {
        //this.elementHeight = elementHeight;
        this.heightText.setText(elementHeight);
    }

    /**
     * @return the elementFontSize
     */
    public String getElementFontSize() {
        return elementFontSize;
    }

    /**
     * @param elementFontSize the elementFontSize to set
     */
    public void setElementFontSize(String elementFontSize) {
        //this.elementFontSize = elementFontSize;
        this.fontSizeText.setText(elementFontSize);
    }

    /**
     * @return the elementColor
     */
    public String getElementColor() {
        return elementColor;
    }

    /**
     * @param elementColor the elementColor to set
     */
    public void setElementColor(String elementColor) {
        //this.elementColor = elementColor;
        this.colorText.setText(elementColor);
    }

    /**
     * @return the elementName
     */
    public String getElementName() {
        return elementName;
    }

    /**
     * @param elementName the elementName to set
     */
    public void setElementName(String elementName) {
        //this.elementName = elementName;
        this.nameText.setText(elementName);
    }

    public void loadProperties(Element currentElement) {
        element = currentElement;
        setElementName(currentElement.getName());
            setElementFontSize(Integer.toString(currentElement.getFontSize()));
            //notes.setText(currentElement.getNote());
            if(currentElement instanceof AbsPlace)
            {
                AbsPlace current= (AbsPlace) currentElement;
                setElementWidth(Integer.toString(current.getWidth()));
                setElementHeight(Integer.toString(current.getHeight()));
            }
            if(currentElement instanceof Transition)
            {
                Transition current= (Transition) currentElement;
                setElementWidth(Integer.toString(current.getWidth()));
                setElementHeight(Integer.toString(current.getHeight()));
            }
    }

}
